CREATE DATABASE ProyectoBan2
USE ProyectoBan2

CREATE TABLE Usuarios(
Id INT NOT NULL AUTO_INCREMENT,
Usuario VARCHAR(100)  NULL,
Contra VARCHAR(200) NULL,
Tipo_U VARCHAR(50) NULL,
PRIMARY KEY(Id)
)

CREATE TABLE Categoria(
IdCate INT NOT NULL AUTO_INCREMENT,
NomCat VARCHAR(25) NULL,
PRIMARY KEY(IdCate)
)



CREATE TABLE Productos(
IdProd INT AUTO_INCREMENT NOT NULL,
IdCate INT NOT NULL,
NombrePro VARCHAR(100) NULL,
Precio DOUBLE(11,2) NULL,
Cantidad INT NULL,
Img VARCHAR(150) NULL,
DescripP VARCHAR(600) NULL,
PRIMARY KEY(IdProd),
FOREIGN KEY (IdCate) REFERENCES Categoria(IdCate)
)

CREATE TABLE TamañosP(
IdT INT AUTO_INCREMENT NOT NULL,
TipoTam VARCHAR(20) NULL,
PrecioT DOUBLE NULL,
PRIMARY KEY(IdT)
)

CREATE TABLE ProductosxTamaños(
IdProd INT NOT NULL,
IdT INT NOT NULL,
FOREIGN KEY (IdProd) REFERENCES Productos (IdProd),
FOREIGN KEY (IdT) REFERENCES TamañosP (IdT)
)

CREATE TABLE Reservaciones(
IdRes INT NOT NULL AUTO_INCREMENT,
IdProd INT NOT NULL,
NombreUs VARCHAR(100) NULL,
ApellidoUs VARCHAR(100) NULL,
TelUs INT (12) NULL,
Tamaño VARCHAR(75) NULL,
CorreoUs VARCHAR(100) NULL,
CantidadR VARCHAR(2) NULL,
PrecioU DOUBLE(11,2) NULL,
TotalPagar DOUBLE(11,2)  NULL,
FechaEntre DATE NULL,
FechaR DATE NULL,
HoraR TIME NULL,
PRIMARY KEY(IdRes),
FOREIGN KEY (IdProd) REFERENCES Productos(IdProd)
)


CREATE TABLE Recubrimiento(
IdRec INT NOT NULL AUTO_INCREMENT,
NomRec VARCHAR(50) NULL,
PRIMARY KEY (IdRec)
)

CREATE TABLE formaspastel(
idForma INT NOT NULL AUTO_INCREMENT,
Forma VARCHAR(50) NULL,
PRIMARY KEY (idForma)
)

CREATE TABLE pisospastel(
idPisos INT NOT NULL AUTO_INCREMENT,
Pisos VARCHAR(50) NULL,
PRIMARY KEY (idPisos)
)


CREATE TABLE Personalizacion(
IdPerz INT NOT NULL AUTO_INCREMENT,
Id INT NOT NULL,
IdRec INT NOT NULL,
idForma  INT NOT NULL,
idPisos INT NOT NULL,
NombreUs VARCHAR(100) NULL,
ApellidoUs VARCHAR(100) NULL,
TelUs INT (12) NULL,
CorreoUs VARCHAR(100) NULL,
Leyenda VARCHAR(150) NULL,
Colores VARCHAR(100) NULL,
Tamaño  VARCHAR(100) NULL,
Fruta  VARCHAR(100) NULL,
Descripcion VARCHAR(500) NULL,
Foto VARCHAR(150) NULL,
PRIMARY KEY (IdPerz),
FOREIGN KEY (IdRec) REFERENCES Recubrimiento(IdRec),
FOREIGN KEY (idForma) REFERENCES formaspastel(idForma),
FOREIGN KEY (Id) REFERENCES Usuarios(Id),
FOREIGN KEY (idPisos) REFERENCES pisospastel(idPisos)
)

CREATE TABLE calificacion(
idCali INT NOT NULL AUTO_INCREMENT,
Id  INT NOT NULL,
IdProd INT NOT NULL, 
Cali VARCHAR(10) NULL,
PRIMARY KEY(idCali),
FOREIGN KEY (Id) REFERENCES Usuarios(Id),
FOREIGN KEY (IdProd) REFERENCES Productos(IdProd)
)



CREATE TABLE Comentarios(
IdComen INT NOT NULL AUTO_INCREMENT,
Coment VARCHAR(350) NULL,
Nombre VARCHAR(50) NULL,
mail VARCHAR(50) NULL,
PRIMARY KEY(IdComen)
)